package com.github.stormwyrm.weather.config

object Constants {
    val EVENT_KEY_WEATHER_STATE: Any = "EVENT_KEY_WORK_STATE"

    val EVENT_KEY_WEATHER_DATA: Any = "EVENT_KEY_WEATHER_DATA"
    val EVENT_KEY_WEATHER_BIND_IMG: Any = "EVENT_KEY_WEATHER_BIND_IMG"
    val EVENT_KEY_CHOOSE_AREA_STATE: Any = "EVENT_KEY_CHOOSE_AREA_STATE"
    val EVENT_KEY_CHOOSE_AREA_PROVICE: Any = "EVENT_KEY_CHOOSE_AREA_PROVICE"
    val EVENT_KEY_CHOOSE_AREA_CITY: Any = "EVENT_KEY_CHOOSE_AREA_CITY"
    val EVENT_KEY_CHOOSE_AREA_COUNTRY: Any = "EVENT_KEY_CHOOSE_AREA_COUNTRY"

}
